root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = [
    "manager",
    "--agent-id",
    "0bc5a45a-ccbc-4377-9644-7e00b8bd3213",
    "--server-url",
    "http://localhost:3000",
    "--driver",
    "inline",
  ]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/agent/*.go"
  delay = 1000
  exclude_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
